/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as FluxoRouteImport } from './routes/fluxo'
import { Route as PremissasRouteImport } from './routes/premissas'
import { Route as ValidacaoRouteImport } from './routes/validacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoRoute = FluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const PremissasRoute = PremissasRouteImport.update({
  id: '/premissas',
  path: '/premissas',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidacaoRoute = ValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/fluxo': typeof FluxoRoute
  '/premissas': typeof PremissasRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/fluxo': typeof FluxoRoute
  '/premissas': typeof PremissasRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/fluxo': typeof FluxoRoute
  '/premissas': typeof PremissasRoute
  '/validacao': typeof ValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apresentacao' | '/fluxo' | '/premissas' | '/validacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apresentacao' | '/fluxo' | '/premissas' | '/validacao'
  id:
    '__root__' | '/' | '/apresentacao' | '/fluxo' | '/premissas' | '/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  FluxoRoute: typeof FluxoRoute
  PremissasRoute: typeof PremissasRoute
  ValidacaoRoute: typeof ValidacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo': {
      id: '/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof FluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premissas': {
      id: '/premissas'
      path: '/premissas'
      fullPath: '/premissas'
      preLoaderRoute: typeof PremissasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validacao': {
      id: '/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof ValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  FluxoRoute: FluxoRoute,
  PremissasRoute: PremissasRoute,
  ValidacaoRoute: ValidacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
